<?php

function bdCrea(PDO $con)
{
 $con->exec(
  'CREATE TABLE IF NOT EXISTS LIBROS (
    LIB_ID INTEGER,
    LIB_IMAGEN MEDIUMBLOB ,
    LIB_TITULO TEXT NOT NULL,
    LIB_AUTOR TEXT NOT NULL,
    LIB_ISBN TEXT NOT NULL,
    LIB_EDITORIAL TEXT NOT NULL,
    LIB_EDICION INTEGER NOT NULL,
    LIB_CATEGORIA TEXT NOT NULL,
    LIB_RESENA TEXT NOT NULL,
    LIB_PRECIO MONEY NOT NULL,
    CONSTRAINT LIB_PK PRIMARY KEY(LIB_ID),
    CONSTRAINT LIB_ISBN_UNQ UNIQUE(LIB_ISBN)
  );'
 );

  $con->exec(
    'CREATE TABLE IF NOT EXISTS USUARIO (
    US_ID INTEGER ,
    US_NOMBRE TEXT NOT NULL,
    US_APELLIDOPATERNO TEXT NOT NULL,
    US_APELLIDOMATERNO TEXT NOT NULL,
    US_CORREOELECTRONICO TEXT NOT NULL,
    US_CONTRASENA TEXT NOT NULL,
    US_CONFIRMARCONTRASENA TEXT NOT NULL,
    US_DIRECCION TEXT NOT NULL,
    CONSTRAINT US_PK PRIMARY KEY(US_ID) 
  );'
  );

   $con->exec(
    'CREATE TABLE IF NOT EXISTS DIARIO (
      DIA_EMOTICON MEDIUMBLOB ,
      DIA_RELATO TEXT NOT NULL
    );'
   );

}
